Repository CallProtector/CallProtector_BE, pull requests merged in 2025-07, with the labels that each got.

#58 Fix: Twilio Token 발급 api 인가 허용
  src/main/java/callprotector/spring/config/WebSecurityConfig.java
Labels: 🐞 BugFix

#56 Refactor: Twilio WebRTC 통화 수신 API 공통응답 형식 적용
  src/main/java/callprotector/spring/web/controller/TwilioVoiceTokenController.java
Labels: 🔨 Refactor

#60 Fix: 프론트 배포 주소 추가
  src/main/java/callprotector/spring/config/WebMvcConfig.java
Labels: 🐞 BugFix

#54 Feat: 상담 내역 상세 조회 기능 구현
  src/main/java/callprotector/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/callprotector/spring/apiPayload/exception/handler/CallSessionNotFoundException.java
  src/main/java/callprotector/spring/apiPayload/exception/handler/CallSttLogNotFoundException.java
  src/main/java/callprotector/spring/config/TwilioMediaStreamsHandler.java
  src/main/java/callprotector/spring/config/WebSecurityConfig.java
  src/main/java/callprotector/spring/domain/CallSttLog.java
  src/main/java/callprotector/spring/repository/CallSttLogRepository.java
  src/main/java/callprotector/spring/service/CallSessionService/CallSessionService.java
  src/main/java/callprotector/spring/service/CallSessionService/CallSessionServiceImpl.java
  src/main/java/callprotector/spring/service/CallSttLogService/CallSttLogService.java
  src/main/java/callprotector/spring/service/CallSttLogService/CallSttLogServiceImpl.java
  src/main/java/callprotector/spring/web/controller/CallSessionController.java
  src/main/java/callprotector/spring/web/dto/response/CallSessionResponseDTO.java
Labels: ✨ Feature

#64 ✨ Feat: 상담 내역 조회 API 구현
  build.gradle
  src/main/java/callprotector/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/callprotector/spring/apiPayload/exception/handler/InvalidCategoryFilterException.java
  src/main/java/callprotector/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/callprotector/spring/repository/AbuseLogRepository.java
  src/main/java/callprotector/spring/repository/AbuseTypeLogRepository.java
  src/main/java/callprotector/spring/repository/CallLogRepository.java
  src/main/java/callprotector/spring/repository/CallSessionRepository.java
  src/main/java/callprotector/spring/repository/CallSessionRepositoryCustom.java
  src/main/java/callprotector/spring/repository/CallSessionRepositoryImpl.java
  src/main/java/callprotector/spring/service/CallSessionService/CallSessionService.java
  src/main/java/callprotector/spring/service/CallSessionService/CallSessionServiceImpl.java
  src/main/java/callprotector/spring/web/controller/CallSessionController.java
  src/main/java/callprotector/spring/web/dto/response/CallSessionResponseDTO.java
Labels: ✨ Feature

#65 📝 Docs: PR 템플릿 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs
